export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPLOAD_RESUME_REQUEST = 'UPLOAD_RESUME_REQUEST';
export const UPLOAD_RESUME_SUCCESS = 'UPLOAD_RESUME_SUCCESS';
export const UPLOAD_RESUME_FAIL = 'UPLOAD_RESUME_FAIL';

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAIL = 'UPDATE_AVATAR_FAIL';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const UPDATE_SKILLS_REQUEST = 'UPDATE_SKILLS_REQUEST';
export const UPDATE_SKILLS_SUCCESS = 'UPDATE_SKILLS_SUCCESS';
export const UPDATE_SKILLS_FAIL = 'UPDATE_SKILLS_FAIL';

export const GET_RESUMES_REQUEST = 'GET_RESUMES_REQUEST';
export const GET_RESUMES_SUCCESS = 'GET_RESUMES_SUCCESS';
export const GET_RESUMES_FAIL = 'GET_RESUMES_FAIL';

export const DELETE_RESUME_REQUEST = 'DELETE_RESUME_REQUEST';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';
export const DELETE_RESUME_FAIL = 'DELETE_RESUME_FAIL'; 